dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)

sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

language: python

python:
  - "3.7"

install:
  - pip install flake8

script:
  - flake8
